### ISSUE TITLE
[Issue]: Telemetry servers are not disabled

### ISSUE THREAD

**Issue by leonardodipace** [an-anime-team/an-anime-game-launcher#44]
### Distro

Manjaro Linux, 64-bit

### Installation Type

AUR

### Describe the issue

The game won't start after I installed the launcher via AUR and applied the patch since a message stating "Telemetry servers are not disabled" appears when I try to start it.

### Reproduction Steps

1. Install an-anime-game-launcher-bin from AUR
2. Start the launcher
3. Download the game
4. Apply the patch
5. Click on "Launch"
6. The notification pops up and the game doesn't start

**Comment by tigersoldier** [comment]
I also had this issue. It turned out that the launcher is checking different host than the patch modifies. Add the following to your `/etc/hosts` file:

```
# Global
0.0.0.0 sg-public-data-api.hoyoverse.com`
# CN
0.0.0.0 log-upload-os.hoyoverse.com
```

**Comment by leonardodipace** [comment]
Editing the `/etc/hosts` file worked for me, thanks!
I think it should be stated somewhere in the docs though.

**Comment by tigersoldier** [comment]
#46 Should fix the discrepancy between the check and the patch

**Comment by unrealapex** [comment]
I am encountering this issue running An Anime Game Launcher on Arch with Lutris. Adding the hosts to `/etc/hosts` did not fix the issue.
