### ISSUE TITLE
Path is not mounted: "/tmp"

### ISSUE THREAD

**Issue by Kisel13** [an-anime-team/an-anime-game-launcher#532]
Getting error when trying predownload an update
ERROR anime_game_launcher::ui::main: Failed to predownload update: Path is not mounted: "/tmp"

Debug info:
Anime Launcher SDK: 1.28.7
Anime Game Core: 1.32.2

gtk: 4.18.6
libadwaita: 1.7.4
pango: 1.56.3
cairo: 1.18.4

\+ my OS is NixOS

**Comment by dy-tea** [comment]
Update the launcher, this is fixed in the latest release.

**Comment by Kisel13** [comment]
Ok, I created fork of "ezKEa/aagl-gtk-on-nix" changed the builder to build a new version, updated launcher on my system, and now, predownload is still not working. But, instead of "Path is not mounted" error, it just stays at 0 B (without any another error in GUI or terminal).
